# Site data
title: Welcome to Jekyll
description: Project description
theme: just-the-docs
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-default-layout

paginate: 10
paginate_path: "/page/:num/"

exclude:
  - docker-compose.yml
  - README.md
  - LICENSE
